apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: goserver
  newName: williamrldb/gitops
  newTag: 6726106dec81d7ad2e2bf05627d4bed46fe05ea8
